# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f3d932ad58a27723d780615ad9d11a7ae87146cf705661b6c9a241c3507bbca1cd897916b092e2fb6d3d2470dc6f687af7594cd40543d3e15050ae85b4c1815d

test:
  secret_key_base: 23bd261fce6d94a59a73aa7b5cc301447c74bd493dd3640e507dd579f02c57a1076720d9455def58a971b9e804442d02783d4e34346c36abecea42adebc4b431

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
